import * as lancedb from '@lancedb/lancedb';
import fs from 'fs';
import path from 'path';

// Define where LanceDB stores its data.
// It will use LANCEDB_PATH from env, or default to a local '.lancedb' folder.
const dbPath = process.env.LANCEDB_PATH || path.resolve(process.cwd(), '.lancedb');

let db: lancedb.Connection | null = null;

/**
 * Ensures the LanceDB directory exists and opens the connection.
 */
export async function getVectorDb(): Promise<lancedb.Connection> {
  if (db) return db;
  
  if (!fs.existsSync(dbPath)) {
    fs.mkdirSync(dbPath, { recursive: true });
  }
  
  db = await lancedb.connect(dbPath);
  return db;
}

/**
 * Gets or creates the knowledge chunks table in LanceDB.
 * We store embedding (vector), chunkId, documentId, documentVersion, and chunk content.
 */
export async function getChunksTable() {
  const conn = await getVectorDb();
  const tableName = 'knowledge_chunks';
  
  // Note: We create the table dynamically when inserting the first records.
  // If it exists, we just open it.
  const tableNames = await conn.tableNames();
  if (tableNames.includes(tableName)) {
    return await conn.openTable(tableName);
  }
  
  return null;
}

/**
 * Type representing a chunk to be inserted into LanceDB.
 * The vector should be an array of floats generated by Ollama.
 */
export interface KnowledgeChunkVector {
  vector: number[];
  chunkId: string;
  documentId: string;
  documentVersion: string;
  status: string;
  checksum: string;
  content: string;
}

/**
 * Inserts or replaces chunks in LanceDB.
 * Reindexing creates a new table or overwrites it if we pass a new table name,
 * but for simplicity, we can just delete old versions or overwrite.
 * The user requested: "Reindexing builds a new index before activating it. A failed reindex must not destroy the previous working index."
 * We will achieve this by creating a table named `knowledge_chunks_${version}`.
 */
export async function createKnowledgeIndex(version: string, chunks: KnowledgeChunkVector[]) {
  const conn = await getVectorDb();
  const tableName = `knowledge_chunks_${version.replace(/[^a-zA-Z0-9]/g, '_')}`;
  
  // If it already exists, drop it to rebuild
  const tableNames = await conn.tableNames();
  if (tableNames.includes(tableName)) {
    await conn.dropTable(tableName);
  }
  
  await conn.createTable(tableName, chunks as any);
  return tableName;
}

/**
 * Perform similarity search on a specific version table.
 */
export async function searchKnowledge(version: string, queryVector: number[], limit = 5) {
  const conn = await getVectorDb();
  const tableName = `knowledge_chunks_${version.replace(/[^a-zA-Z0-9]/g, '_')}`;
  
  const tableNames = await conn.tableNames();
  if (!tableNames.includes(tableName)) {
    return [];
  }
  
  const table = await conn.openTable(tableName);
  
  // LanceDB uses L2 distance by default.
  // We can convert this to a relevance score (e.g. cosine similarity equivalent or normalized distance).
  const results = await table.search(queryVector).limit(limit).toArray();
  
  return results.map((r: any) => {
    // Normalise distance to a relevance score (heuristic: 1 / (1 + distance), or similar)
    // You should calibrate this based on the specific embedding model.
    // Nomic-embed-text generates normalized vectors, so L2 distance relates to cosine similarity.
    // Score = 1 - (distance / 2) roughly for normalized vectors.
    const rawDistance = r._distance || 0;
    const normalisedRelevance = Math.max(0, 1 - (rawDistance / 2));
    
    return {
      chunkId: r.chunkId,
      documentId: r.documentId,
      content: r.content,
      rawDistance,
      normalisedRelevance
    };
  });
}
